[[redirects]]
  from = "/search"
  to = "https://authentication-sample-site.netlify.app/resetpassword/:token"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
